### ISSUE TITLE
AttributeError: type object 'Logger' has no attribute 'store'

### ISSUE THREAD

**Issue by jaraco** [yougov/pmxbot#32]
I've tried installing pmxbot in multiple ways (from source, from old source, with easy_install) and no matter what I do I end up with the following error and no connection to IRC (using the default config and modified config).

Error:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/pmxbot-1106.1.3-py2.7.egg/pmxbot/saysomething.py", line 86, in init_class
    pmxbot.logging.Logger.store,
AttributeError: type object 'Logger' has no attribute 'store'
```

----------------------------------------
- Bitbucket: https://bitbucket.org/yougov/pmxbot/issue/32
- Originally reported by: Stuart Clark
- Originally created at: 2014-03-20T05:18:57.436

**Comment by jaraco** [comment]
It looks like it might be something to do with installing on OS X, it seems to work fine on Debian.

----------------------------------------
Original comment by: Stuart Clark

**Comment by jaraco** [comment]
You can disregard that error. It's a bug in the saysomething module, but I'm pretty sure it can be disregarded. Let me know if you find otherwise.

----------------------------------------
Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Unfortunately my experience said otherwise, while maybe that error wasn't exactly the cause, pmxbot would not run at all on OS X.

----------------------------------------
Original comment by: Stuart Clark

**Comment by jaraco** [comment]
I can assure you that I frequently get that error for the saysomething error. If pmxbot wasn't running on OS X, it's due to something else. That Traceback that occurs occurs in a separate thread. I guess it's conceivable that Python threads on OS X will actually terminate the application, but I'd be highly surprised if that were the case.

The latest version of pmxbot may be more robust with regards to the sayanything functionality. Maybe give it another go?

----------------------------------------
Original comment by: Jason R. Coombs
