### ISSUE TITLE
Strike is broken

### ISSUE THREAD

**Issue by jaraco** [yougov/pmxbot#37]
pmxbot appears to be unable to strike messages.

```
09:33 jaraco test
09:33 !strike 
09:33 pmxbot Hmm.. I didn't find anything of yours to strike!
```

Originally, I suspected this issue was related to the move to Slack, but in watching the logs, I see this error:

```
Traceback (most recent call last):
  File "/app/.heroku/venv/local/lib/python3.4/dist-packages/pmxbot/logging.py", line 401, in strike
    struck = Logger.store.strike(channel, nick, count)
  File "/app/.heroku/venv/local/lib/python3.4/dist-packages/pmxbot/logging.py", line 235, in strike
    date_limit = storage.bson.objectid.ObjectId.from_datetime(
AttributeError: 'module' object has no attribute 'bson'
```

This issue is clearly caused by some delinting done by me, specifically b2e75553773a, and released in 1110.3.

----------------------------------------
- Bitbucket: https://bitbucket.org/yougov/pmxbot/issue/37
- Originally reported by: Jason R. Coombs
- Originally created at: 2014-12-17T15:38:31.591

**Comment by jaraco** [comment]
Restore 'bson' to the storage module namespace. Use imperative import to signal that the import is necessary outside of the usage in this module. Fixes #37.

→ <<cset c6f19d9b89aa>>

----------------------------------------
Original comment by: Jason R. Coombs
