### ISSUE TITLE
maximum recursion depth exceeded intermittently on startup

### ISSUE THREAD

**Issue by jaraco** [yougov/pmxbot#49]
Sometimes when starting in our production environment, I'll find a traceback like this:

```
Error initializing plugin Chuck Norris quips = chucknorris.pmxbot:init.
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 615, in _load_libra
ry_extensions
    init_func = ep.load()
  File "/app/.heroku/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2291, in
 load
    return self.resolve()
  File "/app/.heroku/venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2297, in
 resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/app/.heroku/venv/lib/python3.4/site-packages/chucknorris/pmxbot.py", line 5, in <modul
e>
    from pmxbot.karma import Karma
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/karma.py", line 249, in <module>
    @command(aliases="k")
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 259, in decorate
    return super().decorate(func)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 185, in decorate
    self.register()
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 167, in register
    if self in self._registry:
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 202, in __eq__
    return vars(self) == vars(other)
...
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 202, in __eq__
    return vars(self) == vars(other)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 202, in __eq__
    return vars(self) == vars(other)
RuntimeError: maximum recursion depth exceeded
```

It only happens sometimes, which leads me to believe it's related to the order in which handlers are loaded and that's affected by the PYTHONHASHSEED.

It happens with other plugins as well, not just Chuck Norris.

**Comment by jaraco** [comment]
I suspect the problem lies in how aliases are loaded. In particular a CommandHandler has .aliases and an AliasHandler has a .parent, a circular reference exists between them, and since Handler.__eq__ compares vars(self) and vars(other), those comparisons could in turn compare the aliases and parent attributes.

**Comment by jaraco** [comment]
Aha, and since `vars(self)` may not come in a deterministic order, non-equal aspects might get compared first, avoiding hitting that part of the comparison. But that doesn't yet explain why I haven't seen this in CI tests. Could it be that the behavior is only triggered if some plugins are loaded?

**Comment by jaraco** [comment]
Oh look! The [error does occur](https://travis-ci.org/yougov/pmxbot/jobs/176397539) in CI tests on occasion.
