### ISSUE TITLE
Direct messages don't arrive

### ISSUE THREAD

**Issue by jaraco** [yougov/pmxbot#57]
In the pmxbot code, all messages are sent to channels only. There's no support for sending messages to individuals. However, when connected to the IRC gateway, if one sends a message with a user nick as the channel name, Slack will send that message as a Direct Message to that user.

When switching pmxbot to the Slack native API, however, those messages are no longer arriving. The Slack handler should be adapted to detect and route private messages also.

**Comment by jaraco** [comment]
The issue almost certainly [lies here](https://github.com/yougov/pmxbot/blob/1117.3.7/pmxbot/core.py#L113-L115), where the channel name is always prepended with a literal `#`. I suspect the IRC gateway would resolve #username to @username, but the Slack interface is more particular.

**Comment by jaraco** [comment]
After rolling out this new release, messages prefixed with `@` are failing with this traceback:

```
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 435, in out
    sent = self.allow(channel, s) and self.transmit(channel, s)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/slack.py", line 42, in transmit
    channel.send_message(message)
AttributeError: 'NoneType' object has no attribute 'send_message'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/__main__.py", line 3, in <module>
    pmxbot.core.run()
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 541, in run
    _bot.start()
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/slack.py", line 27, in start
    self.scheduler.run_pending()
  File "/app/.heroku/venv/lib/python3.4/site-packages/tempora/schedule.py", line 150, in run_pending
    self.run(command)
  File "/app/.heroku/venv/lib/python3.4/site-packages/tempora/schedule.py", line 179, in run
    self.dispatch(command.target)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 526, in handle_scheduled
    self._handle_output(handler.channel, clean_results)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 486, in _handle_output
    self.out(message.channel, message, not message.secret)
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/core.py", line 437, in out
    log.exception("Unhandled exception transmitting message: %r", s)
AttributeError: 'bool' object has no attribute 'exception'
/app/.heroku/venv/lib/python3.4/site-packages/cherrypy/process/wspbus.py:243: RuntimeWarning: The main thread is exiting, but the Bus is in the states.STOPPED state; shutting it down automatically now. You must either call bus.block() after start(), or call bus.exit() before the main thread exits.
  'main thread exits.' % self.state, RuntimeWarning)
```

Channel messages are still delivered, however.

**Comment by jaraco** [comment]
Well dang. The API for sending messages to users is nothing like the API for sending messages to channels.
