### ISSUE TITLE
!g command failing

### ISSUE THREAD

**Issue by jmcowden** [yougov/pmxbot#67]
The !google command is failing, with the following output:

`!g test`
`Ouch! An error occurred: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)`

![screen shot 2017-05-30 at 5 02 17 pm](https://cloud.githubusercontent.com/assets/20631821/26610006/c8e55e84-4559-11e7-8bc1-ae50de9794b0.png)

**Comment by lbolla** [comment]
It looks like the `ca-certifcates` on the box running pmxbot is old and needs updating.

**Comment by lbolla** [comment]
It looks like the `ca-certifcates` on the box running pmxbot is old and needs updating.

Full stack trace for reference:
```During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/itertools.py", line 20, in trap_exceptions
    for result in results:
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/itertools.py", line 9, in generate_results
    for item in always_iterable(function()):
  File "/app/.heroku/venv/lib/python3.4/site-packages/pmxbot/commands.py", line 46, in google
    resp = requests.get(url)
  File "/app/.heroku/venv/lib/python3.4/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/newrelic/api/external_trace.py", line 100, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/newrelic/api/external_trace.py", line 100, in dynamic_wrapper
    return wrapped(*args, **kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/app/.heroku/venv/lib/python3.4/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
```

**Comment by jaraco** [comment]
Indeed, the issue appears to be isolated to that particular deployment environment, as the [tests are passing](https://travis-ci.org/yougov/pmxbot/builds/238078496). This gives me confidence that once the certificates are updated in the target environment, the issue will resolve itself.

**Comment by lbolla** [comment]
It turns out, the problems is with the certificates bundled by the latest `requests` release, namely `certifi`.
Latest `certifi` bundles don't work well with `openssl` v.1.0.1 and older (https://pypi.python.org/pypi/certifi).
Luckily, `requests` allows you to use an env var (REQUESTS_CA_BUNDLE) to point to the certs you want to use. Setting it to `/etc/ssl/certs` or whereever one has certificates accepted by openssl, should work.
Alternatively, upgrading openssl should obviously work, too.
