### ISSUE TITLE
Error when slack messages don't have a username

### ISSUE THREAD

**Issue by lbolla** [yougov/pmxbot#78]
It looks like sometimes slack messages don't have a username. Pmxbot should handle them, too.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pmxbot/__main__.py", line 3, in <module>
    pmxbot.core.run()
  File "/usr/local/lib/python3.6/site-packages/pmxbot/core.py", line 559, in run
    _bot.start()
  File "/usr/local/lib/python3.6/site-packages/pmxbot/slack.py", line 32, in start
    self.handle_message(msg)
  File "/usr/local/lib/python3.6/site-packages/pmxbot/slack.py", line 49, in handle_message
    nick = resolve_nick(msg)
  File "/usr/local/lib/python3.6/site-packages/pmxbot/slack.py", line 62, in _resolve_nick_bot_message
    return msg['username']
KeyError: 'username'
```

**Comment by lbolla** [comment]
It looks like not all bots include `username`.
```Some bot_messages also include username and/or icons properties. If present these override the default username or icon for this bot.```
https://api.slack.com/events/message/bot_message
