### ISSUE TITLE
Some integrations not working due to Slack reference resolver

### ISSUE THREAD

**Issue by jaraco** [yougov/pmxbot#81]
Some integrations are failing on the Slack API. For example:

```
jaraco [12:15]
!fogbugz add-user Foo Bar <foo.bar@yougov.com>
pmxbot APP [12:15]
Zoiks! An error occurred: add-user Full Name <email@address.org>
!fogbugz Issue a command to Manuscript (add-user, create-repo, delete-repo).
```

When this error occurs, the traceback shows:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pmxbot/itertools.py", line 20, in trap_exceptions
    for result in results:
  File "/usr/local/lib/python3.6/site-packages/pmxbot/itertools.py", line 9, in generate_results
    for item in always_iterable(function()):
  File "/usr/local/lib/python3.6/site-packages/jaraco/functools.py", line 347, in wrapper
    return retry_call(bound, *r_args, **r_kwargs)
  File "/usr/local/lib/python3.6/site-packages/jaraco/functools.py", line 322, in retry_call
    return func()
  File "/usr/local/lib/python3.6/site-packages/yg/irc/manuscript.py", line 176, in manuscript
    return sub_func(rest)
  File "/usr/local/lib/python3.6/site-packages/yg/irc/manuscript.py", line 75, in add_user
    raise ValueError("add-user Full Name <email@address.org>")
ValueError: add-user Full Name <email@address.org>
Error resolving slack reference
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pmxbot/slack.py", line 100, in _expand
    assert ref is not None
AssertionError
```

**Comment by jaraco** [comment]
I added some logging to our integration and I see this in the logs now:

```
Unrecognized add-user detail: jaraco &lt;fail@example.com&gt;
```

**Comment by jaraco** [comment]
I no longer think the Slack reference resolver is implicated in this issue, but instead suspect the Slack client or Slack itself has changed something about how messages are encoded.

**Comment by jaraco** [comment]
On further consideration, we've only just noticed this issue since the adoption of the Slack native API... so the thing that's changed is we migrated from IRC to Slack.
